apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-android
  namespace: app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
      version: android
  template:
    metadata:
      labels:
        app: java-app
        version: android
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:1.0
        args: ["-text=Hello from ANDROID version"]
        ports:
        - containerPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-ios
  namespace: app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
      version: ios
  template:
    metadata:
      labels:
        app: java-app
        version: ios
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:1.0
        args: ["-text=Hello from IOS version"]
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: app-dev
spec:
  selector:
    app: java-app
  ports:
  - name: http
    port: 80
    targetPort: 5678
